package clases;
// Generated 24-jun-2015 15:56:51 by Hibernate Tools 4.0.0

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String userName;
	private String userPass;

	public Users() {
	}

	public Users(String userName, String userPass) {
		this.userName = userName;
		this.userPass = userPass;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

}
